version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
      # - 443:443
    # environment:
    #   - NGINX_HOST=localhost
    #   - NGINX_PORT=80
    # command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - app-network
    links:
      - nuxt:nuxt
    depends_on:
      - nuxt

  nuxt:
    build:
      context: .
      dockerfile: Dockerfile.nuxt
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - node_modules:/usr/src/app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: ~
